AEP interpolation and blending
GeoscienceAustralia/SWHAQ pull request #7
Opened 2022-06-28 02:03 UTC by kieranricardo

2022-06-28 02:36 UTC, wcarthur commented on scripts/ari_interpolate.py
> +tc_aep = 1.0 / gdp_recurrence_intervals(windspeeds[None, None, :], mu, shape, scale, rate).data
aep = 1.0 - np.exp(-1.0/gpd_recurrence_intervals)

2022-06-28 02:36 UTC, wcarthur commented on scripts/ari_interpolate.py
> +aeps = 1 / ris
aep = 1.0 - np.exp(-1.0/ris)

2022-06-28 02:37 UTC, wcarthur requested changes
Check definition of the AEP in ari_interpolate.py. Will be a subtle difference, but best to be correct from outset

2022-06-28 23:48 UTC, kieranricardo commented
@wcarthur nice catch, I shouldn’t have assumed that AEP = 1 / ARI! this approach makes a lot more sense

2022-06-29 03:54 UTC, wcarthur approved these changes

2022-06-29 03:54 UTC, merged